BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Replays" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"BNetGameID"	TEXT NOT NULL,
	"Name"	TEXT NOT NULL,
	"TimeStamp"	INTEGER NOT NULL,
	"Official"	INTEGER NOT NULL,
	"HighQuality"	INTEGER NOT NULL DEFAULT 0,
	"GameType"	TEXT NOT NULL,
	"Version"	TEXT NOT NULL,
	"Length"	INTEGER NOT NULL,
	"Map"	TEXT NOT NULL,
	"TowerCount"	INTEGER NOT NULL,
	"ChatMessageCount"	INTEGER NOT NULL,
	"Views"	INTEGER NOT NULL DEFAULT 0,
	"Downloads" INTEGER NOT NULL DEFAULT 0,
	"Players"	TEXT NOT NULL,
	"Towers"	TEXT NOT NULL,
	"Chat"	TEXT NOT NULL,
	"UploaderBattleTag"	TEXT NOT NULL,
	"UploaderIP"	TEXT NOT NULL,
	"FileHash"	BLOB NOT NULL,
	"VODURL"	TEXT
);
CREATE INDEX IF NOT EXISTS "IX_ReplayLength" ON "Replays" (
	"Length"
);
CREATE INDEX IF NOT EXISTS "IX_ReplayTowers" ON "Replays" (
	"TowerCount"
);
CREATE INDEX IF NOT EXISTS "IX_ReplayMessages" ON "Replays" (
	"ChatMessageCount"
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ReplayHash" ON "Replays" (
	"FileHash"
);
CREATE TABLE IF NOT EXISTS "GamesPlayed" (
	"PlayerTag"	TEXT NOT NULL,
	"ReplayID"	INTEGER NOT NULL,
	"Race"	TEXT NOT NULL,
	"APM"	INTEGER NOT NULL,
	"Win"	INTEGER,
	"TowerCount"	INTEGER NOT NULL,
	"ChatMessageCount"	INTEGER NOT NULL,
	"NetGoldFed"	INTEGER NOT NULL,
	"NetLumberFed"	INTEGER NOT NULL,
	"TimeToShare"	INTEGER,
	FOREIGN KEY("PlayerTag") REFERENCES "Players"("BattleTag"),
	PRIMARY KEY("PlayerTag","ReplayID")
);
CREATE TABLE IF NOT EXISTS "Players" (
	"BattleTag"	TEXT NOT NULL UNIQUE,
	"HUGames"	INTEGER NOT NULL DEFAULT 0,
	"ORGames"	INTEGER NOT NULL DEFAULT 0,
	"NEGames"	INTEGER NOT NULL DEFAULT 0,
	"UDGames"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("BattleTag")
);
CREATE TABLE IF NOT EXISTS "Chatlogs" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"ReplayID"	INTEGER,
	"ChatText"	TEXT NOT NULL,
	FOREIGN KEY("ReplayID") REFERENCES "Replays"("ID")
);
CREATE TABLE IF NOT EXISTS "Pics" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"ReplayID"	INTEGER,
	"FileName"	TEXT NOT NULL
);
COMMIT;
